#!/usr/bin/env bash

set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$script_dir"

echo "Cleaning React Native build artifacts..."

# Library build output
rm -rf \
  lib \
  dist \
  build \
  coverage \
  .metro-cache \
  .tmp

# React Native Windows Codegen output generated by the consuming Windows build
rm -rf \
  windows/FFmpegKitExtended/codegen

# Library Android / CMake
rm -rf \
  android/.gradle \
  android/.cxx \
  android/.externalNativeBuild \
  android/build

# Library iOS
rm -rf \
  ios/build \
  ios/Pods

# Example caches
rm -rf \
  example/.metro-cache \
  example/.tmp \
  example/coverage \
  example/.macos-runtime/.metro-cache \
  example/.macos-runtime/.tmp \
  example/.macos-runtime/coverage \
  example/.appletvos-runtime/.metro-cache \
  example/.appletvos-runtime/.tmp \
  example/.appletvos-runtime/coverage \
  example/.windows-runtime/.metro-cache \
  example/.windows-runtime/.tmp \
  example/.windows-runtime/coverage

# Example Android / Gradle / CMake
rm -rf \
  example/android/.gradle \
  example/android/.cxx \
  example/android/.externalNativeBuild \
  example/android/build \
  example/android/app/.cxx \
  example/android/app/.externalNativeBuild \
  example/android/app/build

# Example Windows
rm -rf \
  example/windows/build \
  example/windows/x64 \
  example/windows/FFmpegKitExtendedExample/bin \
  example/windows/FFmpegKitExtendedExample/obj \
  example/windows/FFmpegKitExtendedExample.Package/bin \
  example/windows/FFmpegKitExtendedExample.Package/obj \
  example/windows/FFmpegKitExtendedExample.Package/AppPackages \
  example/.windows-runtime \
  example/windows/*.binlog \
  example/windows/*.err \
  example/windows/*.wrn

# Example iOS
rm -rf \
  example/ios/build \
  example/ios/Pods

# Example Apple tvOS
rm -rf \
  example/appletvos/build \
  example/appletvos/Pods \
  example/appletvos/Podfile.lock \
  example/.appletvos-runtime

# Example macOS
rm -rf \
  example/macos/build \
  example/macos/Pods \
  example/macos/Podfile.lock \
  example/.macos-runtime

# TypeScript caches, excluding node_modules
find . \
  -path '*/node_modules' -prune -o \
  -type f -name '*.tsbuildinfo' \
  -exec rm -f {} +

echo "Clean complete."
echo
echo "Rebuild the library:"
echo "  npm run prepare"
echo
echo "Rebuild examples:"
echo "  ./build.sh android"
echo "  ./build.sh ios"
echo "  ./build.sh appletvos"
echo "  ./build.sh macos"
echo "  ./build.sh windows"
