const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');

const root = path.resolve(__dirname, '..');
const packageJson = require(path.join(root, 'package.json'));
const reactNativeConfig = require(path.join(root, 'react-native.config.js'));

function read(relativePath) {
  return fs.readFileSync(path.join(root, relativePath), 'utf8');
}

test('Codegen is consumer-owned instead of pre-generated by the package', () => {
  const config = packageJson.codegenConfig;

  assert.equal(config.includesGeneratedCode, undefined);
  assert.equal(config.outputDir, undefined);
  assert.equal(
    packageJson['react-native-builder-bob'].targets.includes('codegen'),
    false,
  );
  assert.equal(
    packageJson.scripts.prepare.includes('sync-appletvos-codegen'),
    false,
  );
});

test('Android uses the default generated Codegen CMake location', () => {
  const android = reactNativeConfig.dependency.platforms.android;
  assert.equal(android.cmakeListsPath, undefined);
  assert.doesNotMatch(read('android/build.gradle'), /generated\/java/);
});

test('Apple podspec ships handwritten sources only', () => {
  const podspec = read('FFmpegKitExtended.podspec');
  assert.doesNotMatch(podspec, /ios\/generated/);
  assert.doesNotMatch(podspec, /appletvos\/generated/);
  assert.doesNotMatch(podspec, /macos\/generated/);
  assert.match(podspec, /install_modules_dependencies\(s\)/);
});



test('podspec helper methods are namespaced for CocoaPods evaluation', () => {
  const podspec = read('FFmpegKitExtended.podspec');
  assert.match(podspec, /module FFmpegKitExtendedPodspecHelpers/);
  assert.match(podspec, /module_function/);
  assert.match(
    podspec,
    /FFmpegKitExtendedPodspecHelpers\.ffmpeg_kit_extended_app_root/,
  );
  assert.match(
    podspec,
    /FFmpegKitExtendedPodspecHelpers\.ffmpeg_kit_extended_apple_platforms/,
  );
});

test('podspec detects Apple platforms without accessing Config#podfile', () => {
  const podspec = read('FFmpegKitExtended.podspec');
  assert.doesNotMatch(podspec, /Pod::Config\.instance\.podfile\b/);
  assert.match(podspec, /File\.join\(installation_root, ["']Podfile["']\)/);
  assert.match(podspec, /match = source\.match\(/);
});

test('Apple native views include consumer-generated Fabric headers', () => {
  for (const platform of ['ios', 'appletvos', 'macos']) {
    const source = read(`${platform}/RCTFFplayView.mm`);
    assert.match(
      source,
      /<react\/renderer\/components\/FFmpegKitExtendedSpec\/ComponentDescriptors\.h>/,
    );
    assert.match(
      source,
      /<react\/renderer\/components\/FFmpegKitExtendedSpec\/RCTComponentViewHelpers\.h>/,
    );
    assert.doesNotMatch(source, /#import "generated\//);
  }
});

test('example build scripts do not manually generate or copy Apple Codegen', () => {
  const buildScript = read('build.sh');
  assert.doesNotMatch(buildScript, /generate_appletvos_codegen/);
  assert.doesNotMatch(buildScript, /sync_appletvos_codegen_to_runtime/);
  assert.doesNotMatch(buildScript, /generate_macos_codegen/);
  assert.doesNotMatch(buildScript, /sync_macos_codegen_to_runtime/);
  assert.doesNotMatch(buildScript, /\.appletvos-codegen/);
  assert.doesNotMatch(buildScript, /\.macos-codegen/);
});

test('Windows keeps consumer build-time Windows Codegen configuration', () => {
  const windows = packageJson.codegenConfig.windows;
  assert.equal(windows.outputDirectory, 'windows/FFmpegKitExtended/codegen');
  assert.deepEqual(windows.generators, ['modulesWindows', 'componentsWindows']);
  assert.equal(windows.namespace, 'FFmpegKitExtendedCodegen');
});

test('Windows native module exposes the structured v2 log event bridge', () => {
  const header = read('windows/FFmpegKitExtended/FFmpegKitExtended.h');
  const implementation = read('windows/FFmpegKitExtended/FFmpegKitExtended.cpp');

  assert.match(header, /#include "codegen\/NativeFFmpegKitExtendedDataTypes\.g\.h"/);
  assert.match(header, /#include "codegen\/NativeFFmpegKitExtendedSpec\.g\.h"/);
  assert.match(header, /REACT_TURBO_MODULE\(FFmpegKitExtended\)/);
  assert.match(header, /REACT_EVENT\(onLogEvent\)/);
  assert.match(header, /std::function<void\(LogEvent\)> onLogEvent/);
  assert.match(header, /REACT_METHOD\(installLogBridge\)/);
  assert.match(header, /REACT_METHOD\(uninstallLogBridge\)/);
  assert.match(implementation, /api::enableLogCallbackV2\(&handleLogEvent, state\.get\(\)\)/);
  assert.match(implementation, /api::enableLogCallbackV2\(nullptr, nullptr\)/);
  assert.match(implementation, /class OwnedLogMessage/);
  assert.match(implementation, /api::releaseOwnedLogMessage\(value\)/);
  assert.match(implementation, /std::move\(message\)/);
});

test('v2 log bridge keeps native and Web event ownership explicit', () => {
  const nativeSpec = read('src/NativeFFmpegKitExtended.ts');
  const nativeApi = read('cpp/FFmpegKitDynamicApi.h');
  const nativeImpl = read('cpp/FFmpegKitExtendedImpl.cpp');
  const webBackend = read('src/platform/backend.web.ts');
  const wasmLoader = read('src/platform/web/wasm-loader.ts');
  const session = read('src/session.ts');

  assert.match(nativeSpec, /readonly onLogEvent: EventEmitter<LogEvent>/);
  assert.match(nativeSpec, /installLogBridge\(\): void/);
  assert.match(nativeSpec, /uninstallLogBridge\(\): void/);
  assert.match(nativeApi, /std::int64_t sessionId/);
  assert.match(nativeApi, /std::int64_t sequence/);
  assert.match(nativeApi, /std::int32_t level/);
  assert.match(nativeApi, /char \*ownedMessage/);
  assert.match(nativeApi, /void \*userData/);
  assert.match(nativeApi, /releaseOwnedLogMessage/);
  assert.match(nativeImpl, /std::string message = owned\.value/);
  assert.match(nativeImpl, /api::releaseOwnedLogMessage\(value\)/);
  assert.match(nativeImpl, /emitOnLogEvent\(/);
  assert.match(webBackend, /addFunction\(this\.handleWasmLogEvent, 'vjjipp'\)/);
  assert.match(webBackend, /this\.call\('ffmpeg_kit_free'\)\(pointer\)/);
  assert.match(wasmLoader, /addFunction\?/);
  assert.match(wasmLoader, /removeFunction\?/);
  assert.match(session, /!directLogEvents/);
  assert.match(session, /subscribeLogEvents\(this\.sessionId/);
  assert.doesNotMatch(nativeImpl, /reinterpret_cast<.*ownedMessage/);
});
