const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');

const root = path.resolve(__dirname, '..');
const packageJson = require(path.join(root, 'package.json'));
const reactNativeConfig = require(path.join(root, 'react-native.config.js'));

function read(relativePath) {
  return fs.readFileSync(path.join(root, relativePath), 'utf8');
}

test('Codegen is consumer-owned instead of pre-generated by the package', () => {
  const config = packageJson.codegenConfig;

  assert.equal(config.includesGeneratedCode, undefined);
  assert.equal(config.outputDir, undefined);
  assert.equal(
    packageJson['react-native-builder-bob'].targets.includes('codegen'),
    false,
  );
  assert.equal(
    packageJson.scripts.prepare.includes('sync-appletvos-codegen'),
    false,
  );
});

test('Android uses the default generated Codegen CMake location', () => {
  const android = reactNativeConfig.dependency.platforms.android;
  assert.equal(android.cmakeListsPath, undefined);
  assert.doesNotMatch(read('android/build.gradle'), /generated\/java/);
});

test('Apple podspec ships handwritten sources only', () => {
  const podspec = read('FFmpegKitExtended.podspec');
  assert.doesNotMatch(podspec, /ios\/generated/);
  assert.doesNotMatch(podspec, /appletvos\/generated/);
  assert.doesNotMatch(podspec, /macos\/generated/);
  assert.match(podspec, /install_modules_dependencies\(s\)/);
});

test('Apple native views include consumer-generated Fabric headers', () => {
  for (const platform of ['ios', 'appletvos', 'macos']) {
    const source = read(`${platform}/RCTFFplayView.mm`);
    assert.match(
      source,
      /<react\/renderer\/components\/FFmpegKitExtendedSpec\/ComponentDescriptors\.h>/,
    );
    assert.match(
      source,
      /<react\/renderer\/components\/FFmpegKitExtendedSpec\/RCTComponentViewHelpers\.h>/,
    );
    assert.doesNotMatch(source, /#import "generated\//);
  }
});

test('example build scripts do not manually generate or copy Apple Codegen', () => {
  const buildScript = read('build.sh');
  assert.doesNotMatch(buildScript, /generate_appletvos_codegen/);
  assert.doesNotMatch(buildScript, /sync_appletvos_codegen_to_runtime/);
  assert.doesNotMatch(buildScript, /generate_macos_codegen/);
  assert.doesNotMatch(buildScript, /sync_macos_codegen_to_runtime/);
  assert.doesNotMatch(buildScript, /\.appletvos-codegen/);
  assert.doesNotMatch(buildScript, /\.macos-codegen/);
});

test('Windows keeps consumer build-time Windows Codegen configuration', () => {
  const windows = packageJson.codegenConfig.windows;
  assert.equal(windows.outputDirectory, 'windows/FFmpegKitExtended/codegen');
  assert.deepEqual(windows.generators, ['modulesWindows', 'componentsWindows']);
  assert.equal(windows.namespace, 'FFmpegKitExtendedCodegen');
});
