# Generated by ffmpeg_kit_flutter:configure
set(FFMPEG_KIT_PATH "D:/Projects/ffmpeg-kit-extended/flutter/example/windows/ffmpeg_kit_bundle/bundle-base-windows-x86_64-shared-gpl" CACHE STRING "Local Bundle" FORCE)
