name: ffmpeg_kit_extended_flutter
description: A comprehensive Flutter plugin for executing FFmpeg, FFprobe, and FFplay commands using FFmpeg 9.0.1 API. Supports Android, iOS, macOS, Linux, Windows, and WebAssembly web builds.
repository: https://github.com/akashskypatel/ffmpeg-kit-extended
issue_tracker: https://github.com/akashskypatel/ffmpeg-kit-extended/issues
homepage: https://github.com/akashskypatel/ffmpeg-kit-extended
documentation: https://github.com/akashskypatel/ffmpeg-kit-extended/tree/master/flutter/doc
version: 0.6.2

topics:
  - ffmpeg
  - media-processing
  - transcoding
  - media-tagging
  - ffmpeg-kit

environment:
  sdk: ">=3.12.0 <4.0.0"
  flutter: ">=3.44.0"

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: FfmpegKitExtendedFlutterPlugin
      windows:
        pluginClass: FfmpegKitExtendedFlutterPlugin
      android:
        package: com.akashskypatel.ffmpeg_kit_extended_flutter
        pluginClass: FfmpegKitExtendedFlutterPlugin
      ios:
        pluginClass: FfmpegKitExtendedFlutterPlugin
        fileName: FfmpegKitExtendedFlutterPlugin.h
      macos:
        pluginClass: FfmpegKitExtendedFlutterPlugin
        fileName: FfmpegKitExtendedFlutterPlugin.h
      web:
        pluginClass: FfmpegKitExtendedFlutterWeb
        fileName: ffmpeg_kit_extended_flutter_web.dart

dependencies:
  code_assets: ^1.2.1
  crypto: ^3.0.7
  data_assets: ^0.20.0
  ffi: ^2.2.0
  ffigen_js:
    git:
      url: https://github.com/akashskypatel/ffigen_js.git
      ref: fix/uint64-wasm-interop
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  hooks: ^2.0.2
  logging: ^1.3.0
  meta: ^1.18.0
  path: ^1.9.1
  plugin_platform_interface: ^2.1.8
  web: ^1.1.1
  yaml: ^3.1.3

dev_dependencies:
  ffigen: ^21.0.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  leak_tracker_flutter_testing: ^3.0.10
  lints: ^6.1.0
  test: ^1.26.3
